### ISSUE TITLE
[NTTCP-10] apiConnect does not respect timeouts

### ISSUE THREAD

**Issue by qnikst** [haskell-distributed/network-transport-tcp#22]
[Imported from JIRA. Reported by Facundo Dominguez @facundominguez)  as [NTTCP-10](https://cloud-haskell.atlassian.net/browse/NTTCP-10) on 2015-05-19 16:53:40]
{{createConnectionTo}} calls [findRemoteEndpoint|https://github.com/haskell-distributed/network-transport-tcp/blob/773ca26f69d79226e401665f7e6589d5c7f00977/src/Network/Transport/TCP.hs#L1052] and {{findRemoteEndpoint}} may block indefinitely waiting for network operations to complete.

This call should happen under a {{timeout}} call so connect terminates when it blocks for too long.

Actually, only the {{Network.Socket.connect}} call happens under a {{timeout}} call. An almost immediately following {{recvInt32}} call can block indefinitely too.

**Comment by avieth** [comment]
Should close this. It's fixed here https://github.com/haskell-distributed/network-transport-tcp/commit/b4274f901fcc8ace3be468649b02b396901d9874

**Comment by qnikst** [comment]
Thanks
