### ISSUE TITLE
Reconnect and CloseEndpoint tests fail non-deterministically

### ISSUE THREAD

**Issue by mboes** [haskell-distributed/network-transport-tcp#32]
These tests sometimes fail, indicating that the tests are either poorly written, and should be fixed, or that there is a race condition in network-transport-tcp.

**Comment by qnikst** [comment]
According to error logs in Travis last error happened when tests fix were not landed (at least lines with error differ from current state). Also I was not able to reproduce errors using either stack build or travis.

If this error happen for you, can you submit error log?

**Comment by mboes** [comment]
Ok I just ran 20 times on my local machine with the latest version and all 20 runs succeed. Will reopen if I see this again.
