### ISSUE TITLE
Can you patch release please...?

### ISSUE THREAD

**Issue by hyperthunk** [haskell-distributed/network-transport-tcp#77]
I'm currently working on getting distributed-process compiling with the latest stackage nightly, and GHC 8.6.1. This is proving very awkward, because in #61 (c7fd793) you introduced a breaking change to the API viz the use of `defaultTCPAddr`, and now all the tests and benchmarks are being updated to observe that API, I can no longer support older versions of GHC, since the older packaged versions of this library had a different type signature for `createTransport`.

I can either use CPP to conditionally compile those tests, or just point to the latest tag on github, but I suspect the latter will be frowned upon by @qnikst, and it does feel rather bad to test an install from lts-9.2 but get the n-t-tcp library from elsewhere...

**Comment by facundominguez** [comment]
Hello, Tim. I'll get to it when I have some time, but I wouldn't mind if you upload releases to hackage sooner.

**Comment by hyperthunk** [comment]
Cool, thanks @facundominguez. I'll finish up the distributed-process patches and get them merged first, then bump everything to the latest and release to hackage. Will coordinate with @qnikst over this week about it.

**Comment by maximedenes** [comment]
Any chance this can happen soon? It would be useful to have a GHC 8.6.5 compatible release of all these packages.

**Comment by hyperthunk** [comment]
I'm afraid I don't have access to a development environment at the moment,
and unlikely to be able to produce a release before the first week in
December.

Can you can pull together sooner than that, Facundo?

**Comment by facundominguez** [comment]
Maybe. What is exactly what needs to be done to in `n-t-tcp` to help downstream?

**Comment by qnikst** [comment]
With https://github.com/haskell-distributed/network-transport-tcp/pull/87 n-t-tcp is buildable under GHC-8.6.5.  `rank1dynamic` and `n-t` are buildable out of the box.

**Comment by facundominguez** [comment]
I've released 0.7.0 with what we had on master, and 0.6.1 by removing #61 from it. Feel free to reopen if something looks amiss still.
