### ISSUE TITLE
Support network >= 3

### ISSUE THREAD

**Issue by jbransen** [haskell-distributed/network-transport-tcp#88]
Version 3 of [the network package](http://hackage.haskell.org/package/network-3.0.0.0) has been out there for 1,5 years now, it would be great if this package could be updated to support it.

**Comment by facundominguez** [comment]
Thanks @jbransen. A quick pass over the code seemed to make it.

**Comment by jbransen** [comment]
Oh wow, that was fast. Thanks a lot!
