### ISSUE TITLE
allow network-3.2

### ISSUE THREAD

**Issue by ysangkok** [haskell-distributed/network-transport-tcp#94]
the cabal file doesn't allow this version of the network dependency:

https://github.com/haskell-distributed/network-transport-tcp/blob/master/network-transport-tcp.cabal#L34

it would be nice if it did, see

* https://github.com/commercialhaskell/stackage/issues/7381

Note that Hackage maintainers can now [receive notifications when dependencies go out of bound](https://discourse.haskell.org/t/hackage-dep-bound-notifications-and-uploader-endorsements-for-new-users/8342?u=janus).

**Comment by LaurentRDC** [comment]
No code changes were needed, so I published [a revision on Hackage](https://hackage.haskell.org/package/network-transport-tcp-0.8.3/revisions/).

I have updated my Hackage notifications to get alerts. Thanks!
